[package]
name = "cli_tools"
version = "0.1.0"
authors = ["layonthehorn <thomaspdressel@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap = "2.33.3"
termcolor = "1.1.0"
glob = "0.3.0"